AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Versant nexus Service

  Nexus artifact service

Parameters:
  Domain:
    Type: String
    Description: 'Application Platform'

  System:
    Type: String
    Description: 'Application System'

  Component:
    Type: String
    Description: 'Application Component'

  CodeBranch:
    Type: String
    Description: 'Name of deployment branch'

  ClusterName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of ECS cluster

  ClusterTaskIamRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: IAM role ARN for task ECS opperations.

  ClusterAlbListenerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of ECS cluster

  ClusterSecurityGroupId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: ID of cluster security group

  ContainerImage:
    Type: String
    Description: Container image

  ContainerTag:
    Type: String
    Description: Container tag

  ContainerCpu:
    Type: Number
    Description: Container CPU allocation units. 1024 is 1 CPU. Value may equal fraction of a CPU.

  ContainerMemory:
    Type: Number
    Description: Container memory in megabytes

  ContainerDesiredCount:
    Type: Number
    Description: How many copies of the service task to run

  ContainerPort:
    Type: Number
    Description: Port container will listen on

  AlbRulePriority:
    Type: Number
    Description: The priority for the routing rule added to the load balancer.

  AlbRulePath:
    Type: String
    Description: A path on the public load balancer that this service
      should be connected to. Use * to send all load balancer
      traffic to this service.

  VpcId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Account VPC ID

  VpcSubnets:
    Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
    Description: Account subnets

  NexusAdminPassword:
    Type: String
    Description: Nexus admin password
    NoEcho: true

  PgUser:
    Type: String
    Description: Postgres user

  PgPasswd:
    Type: String
    Description: Postgres password
    NoEcho: true

  PgHost:
    Type: String
    Description: Postgres hostname

  PgPort:
    Type: Number
    Description: Postgres port
    Default: 5432

  RdsSecurityGroupId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Security group ID for RDS access

Resources:
  PersistentStorageFs:
    Type: AWS::EFS::FileSystem
    DeletionPolicy: RetainExceptOnCreate
    UpdateReplacePolicy: Retain
    Properties:
      Encrypted: true

  PersistentStorageAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref PersistentStorageFs
      PosixUser:
        # the group and user id are what are used by the Nexus docker image
        Gid: '200'
        Uid: '200'
      RootDirectory:
        CreationInfo:
          OwnerGid: '200'
          OwnerUid: '200'
          Permissions: '775'
        Path: /nexus-data

  NexusMountTarget0:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref PersistentStorageFs
      SubnetId: !Select [ 0, !Ref VpcSubnets ]
      SecurityGroups:
        - !Ref ClusterSecurityGroupId

  NexusMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref PersistentStorageFs
      SubnetId: !Select [ 1, !Ref VpcSubnets ]
      SecurityGroups:
        - !Ref ClusterSecurityGroupId

  NexusMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref PersistentStorageFs
      SubnetId: !Select [ 2, !Ref VpcSubnets ]
      SecurityGroups:
        - !Ref ClusterSecurityGroupId

  NexusMountSgIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ClusterSecurityGroupId
      IpProtocol: tcp
      FromPort: 2049
      ToPort: 2049
      SourceSecurityGroupId: !Ref ClusterSecurityGroupId

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    # NOTE: NexusMountTarget depends exists because propegating DNS entires for EFS mounts can
    # be slow and result in failing task launches; even failed CloudFormation deployments. By
    # adding these dependencies here we give greater time for the record to propegate. This
    # issue really only occurs on first deployment since mount targets probably aren't changing
    # often if at all.
    DependsOn:
      - NexusMountTarget0
      - NexusMountTarget1
      - NexusMountTarget2
      - RdsSgIngressRule
    Properties:
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Family: !Sub ${Component}-${CodeBranch}
      Cpu: !Ref ContainerCpu
      Memory: !Ref ContainerMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ClusterTaskIamRoleArn
      TaskRoleArn: !Ref TaskIamRole
      Volumes:
        - Name: nexus-data
          EFSVolumeConfiguration:
            FilesystemId: !Ref PersistentStorageFs
            AuthorizationConfig:
              AccessPointId: !Ref PersistentStorageAccessPoint
            RootDirectory: /
            TransitEncryption: ENABLED
      ContainerDefinitions:
        - Name: !Ref Component
          Image: !Sub '${ContainerImage}:${ContainerTag}'
          Ulimits:
            # NOTE: This is the ECS Fargate default but also the stated recommendation from
            # sonatype. It's unnecessary but here for clarity.
            - Name: nofile
              SoftLimit: 65536
              HardLimit: 65536
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          MountPoints:
            - SourceVolume: nexus-data
              ContainerPath: /nexus-data
          Environment:
            - Name: NEXUS_DATASTORE_NEXUS_JDBCURL
              Value: !Sub 'jdbc:postgresql://${PgHost}:${PgPort}/nexus'
            - Name: NEXUS_DATASTORE_NEXUS_USERNAME
              Value: !Ref PgUser
            - Name: NEXUS_DATASTORE_NEXUS_PASSWORD
              Value: !Ref PgPasswd
          DockerLabels:
            com.datadoghq.tags.domain: !Ref Domain
            com.datadoghq.tags.system: !Ref System
            com.datadoghq.tags.component: !Ref Component
            com.datadoghq.tags.code_branch: !Ref CodeBranch
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: !Sub '/aws/ecs/${ClusterName}/${AWS::StackName}'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: app

  Service:
    Type: AWS::ECS::Service
    DependsOn: AlbListenerRule
    Properties:
      ServiceName: !Ref Component
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      EnableECSManagedTags: true
      PropagateTags: TASK_DEFINITION
      EnableExecuteCommand: true
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DesiredCount: !Ref ContainerDesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref ClusterSecurityGroupId
          Subnets: !Ref VpcSubnets
          AssignPublicIp: ENABLED   # Enabled because this runs in public subnet
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: !Ref Component
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref AlbTargetGroup
      HealthCheckGracePeriodSeconds: 60


  AlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 4
      HealthyThresholdCount: 2
      TargetType: ip
      Port: !Ref ContainerPort
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref VpcId

  AlbListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref AlbTargetGroup
          Type: forward
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref AlbRulePath
      ListenerArn: !Ref ClusterAlbListenerArn
      Priority: !Ref AlbRulePriority


  RdsSgIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RdsSecurityGroupId
      IpProtocol: tcp
      FromPort: !Ref PgPort
      ToPort: !Ref PgPort
      SourceSecurityGroupId: !Ref ClusterSecurityGroupId

  TaskIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies: []
